generate_methods_out_schema = {
    "response_mime_type": "application/json",
    "response_schema": {
        "type": "object",
        "properties": {
            "methods": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["equation"],
                    "properties": {
                        "id": {
                            "type": "string",
                            "description": "Method ID (optional, autogenerated if missing)"
                        },
                        "description": {
                            "type": "string",
                            "description": "Human-readable description"
                        },
                        "equation": {
                            "type": "string",
                            "description": "Mathematical equation or expression"
                        },
                        "params": {
                            "type": "array",
                            "items": { "type": "string" },
                            "description": "Ordered parameter names"
                        },
                        "origins": {
                            "type": "array",
                            "items": { "type": "string" },
                            "description": "Origin per parameter (e.g. 'self' or external id)"
                        }
                    }
                }
            }
        },
        "required": ["methods"]
    }
}
